services:
  webserver:
    image: nginx:1.28-alpine
    ports:
      - "8080:80"
    volumes:
      - ./docker/feeds:/usr/share/nginx/html/feeds/
      - ./docker/cache:/usr/share/nginx/html/cache/
      - ./docker/files:/usr/share/nginx/html/files/

  atom-creator:
    profiles:
      - atom-creator
    build:
      context: .
    image: atom-creator
    volumes:
      - ./docker/test.yaml:/config.yaml
      - ./docker/cache:/cache
      - ./docker/feeds:/feeds
