services:
  webserver:
    image: nginx:1.28-alpine
    ports:
      - "8080:80"
    volumes:
      - ./output:/usr/share/nginx/html/feed/
      - ./src/test/resources/files:/usr/share/nginx/html/files/
