services:
  webserver:
    image: nginx:1.28-alpine
    ports:
      - "8080:80"
    volumes:
      - ./docker/data:/usr/share/nginx/html/

  atom-creator:
    container_name: atom-creator
    build:
      context: .
    image: atom-creator
    environment:
      PUBLIC_URL: http://localhost:8080
    volumes:
      - ./docker/test.yaml:/config.yaml
      - ./docker/data:/data

  ofelia:
    image: mcuadros/ofelia:latest
    depends_on:
      atom-creator:
        condition: service_completed_successfully
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      ofelia.job-run.atom-creator.schedule: "0 0 1 * * *"
      ofelia.job-run.atom-creator.command: "sh -c 'docker restart atom-creator'"
      ofelia.job-run.atom-creator.image: "docker:cli"
      ofelia.job-run.atom-creator.volume: "/var/run/docker.sock:/var/run/docker.sock"
